// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW8QEvXdB2Nre7muJurynlqEDXb5sXofU',
    appId: '1:983718236250:android:eef3905ec0e657cd66c863',
    messagingSenderId: '983718236250',
    projectId: 'dth-65e72',
    storageBucket: 'dth-65e72.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMsBPeZqpBKjA9jbXn2WjARlzf6-A8Qgo',
    appId: '1:983718236250:ios:8bc431a5d9596e3466c863',
    messagingSenderId: '983718236250',
    projectId: 'dth-65e72',
    storageBucket: 'dth-65e72.firebasestorage.app',
    androidClientId: '983718236250-ind22dp932fm27o5qfnt8tlnfcqn0se5.apps.googleusercontent.com',
    iosClientId: '983718236250-bcnqerhm519i665dmenescqucbphp8r3.apps.googleusercontent.com',
    iosBundleId: 'com.dth.dthapp',
  );

}